### ISSUE TITLE
number of decoder layers impact

### ISSUE THREAD

**Issue by jihwanp** [hitachi-rd-cv/qpic#10]
Hi, thanks for interesting work.
Does the number of decoder layers have a significant impact on performance like in detr?
And I cant find how much v100 you've used. maybe 8?

**Comment by tamtamz** [comment]
Thanks for your comments.
We did not investigate the impact of the number of decoder layers.
We used 8 GPUs.

**Comment by jihwanp** [comment]
@tamtamz thanks 
i have one more question. what is test_map_thesis and test_map_all ?

**Comment by tamtamz** [comment]
test_map_all means that mAP is evaluated over all the verbs, while test_map_thesis means that mAP is evaluated over the target verbs, excluding stand, walk, etc.
Note that the original evaluation code should be used for precise evaluation.
