### ISSUE TITLE
How to get the file logs/checkpoint.pth？

### ISSUE THREAD

**Issue by Lunarli** [hitachi-rd-cv/qpic#11]
Thanks for your interesting work！
Now I have a question about how to get the file logs/checkpoint.pth，I have  not see the file from your google drive.
Desire to your reply.

**Comment by tamtamz** [comment]
Thanks for your comments.
Do you mean the pre-trained parameters for the V-COCO training?
If so, as described in the preparation section, you have to pre-train QPIC with COCO by yourself for the V-COCO training. The file logs/checkpoint.pth is the pre-trained parameters.

**Comment by Lunarli** [comment]
I‘m new to this field，and I don't know how to pre-train QPIC with COCO by myself  whitout the file checkpoint.pth.
Can you tell more details about how to realize the VCOCO train  process if you are free？
（In your paper you said that  initialize the network with the parameters of DETR [2] trained with the COCO dataset，should I download this framework？）

**Comment by tamtamz** [comment]
See #4 for the details.

**Comment by Lunarli** [comment]
ok,I will try it,thanks for your reply!
