### ISSUE TITLE
Some useless steps in focal loss

### ISSUE THREAD

**Issue by YueLiao** [hitachi-rd-cv/qpic#12]
![image](https://user-images.githubusercontent.com/30544357/114840866-d1ff5d00-9e09-11eb-978c-a8a432037bf9.png)
Thx for your interesting work! The neg_weights is meaningful only in heatmap based problem, e.g., Gaussian based detection. Removing those steps may avoid some misunderstanding.

**Comment by tamtamz** [comment]
Thanks for pointing out. I fixed it.
