### ISSUE TITLE
Different AP Results for pre-trained VCOCO models

### ISSUE THREAD

**Issue by cancam** [hitachi-rd-cv/qpic#18]
Hi folks,

First of all, thank you for sharing this repository. I would like to ask a specific question about the evaluation results of provided pre-trained V-COCO models. I followed the instructions you provided (for constructing annotation files for V-COCO and obtaining pickle files) to get the results. However, comparing with the V-COCO results in the table, I got different average role ap results. For instance, I am providing the output of R-50 QPIC, scenario 1 Role AP result in the attached screenshot. I am wondering possible reasons for the issue, could you please provide assistance about this?

![qpic_resnet50_sc1_roleap](https://user-images.githubusercontent.com/5897289/123967873-66b43880-d9bf-11eb-95d1-d8647114e179.png)

**Comment by tamtamz** [comment]
Please see #7.

**Comment by cancam** [comment]
Thank you for your help. I can reproduce the results in the paper now.
