### ISSUE TITLE
Distance AP 

### ISSUE THREAD

**Issue by jihwanp** [hitachi-rd-cv/qpic#19]
Hi I have a question about distance-wise ap.
![image](https://user-images.githubusercontent.com/70801434/124226458-1a463580-db44-11eb-806b-eb9f8dd064ac.png)

Does the hoi instance, which participated in calculating ap, correspond to distance=0.1 when the distance between human & center box is between 0.1 and 0.2?

Or I would fully appreciate it if  you could provide code for calculate distance wise ap.
Thanks

**Comment by cjw2021** [comment]
It's a good idea to illustrate the performance by spatial.
I write the code to calculate these two APs based on [GGNet's code](https://github.com/SherlockHolmes221/GGNet/blob/main/src/lib/eval/hico_eval_de_ko.py). The distance-wise ap looks similar to this graph. However, the area-wise ap is different from yours.
If you could provide the evaluation code, I would appreciate it a lot.

**Comment by thunderbolt-fire** [comment]
> It's a good idea to illustrate the performance by spatial. I write the code to calculate these two APs based on [GGNet's code](https://github.com/SherlockHolmes221/GGNet/blob/main/src/lib/eval/hico_eval_de_ko.py). The distance-wise ap looks similar to this graph. However, the area-wise ap is different from yours. If you could provide the evaluation code, I would appreciate it a lot.

hellow , do you deal with this problem? Could you provide the code?
