### ISSUE TITLE
Reproduction the result on VCOCO dataset

### ISSUE THREAD

**Issue by SherlockHolmes221** [hitachi-rd-cv/qpic#3]
Hi, I can reproduce the result on HICO-DET dataset, but just get 51 on V-COCO dataset, could you please provide the log.txt? I am not sure where I am wrong. Thanks.

**Comment by tamtamz** [comment]
[log.txt](https://github.com/hitachi-rd-cv/qpic/files/6138146/log.txt)
I attached the log file.

**Comment by mytk2012** [comment]
I got the result is 50.78，do you fix it?

**Comment by cjw2021** [comment]
Hi, could you please also provide the log.txt of HICO-Det. I have trained the model on 4 GPUs. Although I got a lower mAP, the mean max recall is higher than the model you provide.

**Comment by tamtamz** [comment]
[log.txt](https://github.com/hitachi-rd-cv/qpic/files/6600614/log.txt)
I attached the log file of the training for HICO-DET.

**Comment by Charles-Xie** [comment]
> [log.txt](https://github.com/hitachi-rd-cv/qpic/files/6600614/log.txt)
> I attached the log file of the training for HICO-DET.

Hi,
thanks for sharing!
I try to reproduce your r50 result on HICO-DET, but the performance during final epochs are around 28.3 mAP. From the log.txt you shared I can see that your model has a stable performance of 29.0+ mAP in the last epochs, which is obviously better than what I reproduced.
I am quite sure that I follow all the steps in the README. Can you give me some tips about this performance difference? Like, maybe you used different training hyper-parameters, additional processing on the annotations, or pre-training object detector on the hico-det?
Thanks a lot!

**Comment by Charles-Xie** [comment]
> [log.txt](https://github.com/hitachi-rd-cv/qpic/files/6600614/log.txt)
> I attached the log file of the training for HICO-DET.


Hi,
thanks for sharing!
I try to reproduce your r50 result on HICO-DET, but the performance during final epochs are around 28.3 mAP. From the log.txt you shared I can see that your model has a stable performance of 29.0+ mAP in the last epochs, which is obviously better than what I reproduced.
I am quite sure that I follow all the steps in the README. Can you give me some tips about this performance difference? Like, maybe you used different training hyper-parameters, additional processing on the annotations, or pre-training object detector on the hico-det?
Thanks a lot!

**Comment by mytk2012** [comment]
I reproduce result on HICO-DET,but it was 17 mAP only.And you?

**Comment by Charles-Xie** [comment]
> I reproduce result on HICO-DET,but it was 17 mAP only.And you?

I tried to run QPIC on HICO-DET for several times, the results vary in a range of  28.6 ~29.2.
