### ISSUE TITLE
How to convert the pretrained DETR model for V-COCO style?

### ISSUE THREAD

**Issue by weiyunfei** [hitachi-rd-cv/qpic#9]
Hi! Sorry for bothering again. When I tried to train a V-COCO model, I found that the object classifier of the pre-trained DETR model is only 81-way (including background), while in #6 you claimed that the V-COCO model has an 82-way object classifier (including background and a missing category id). So what should I do to convert the classifier parameters from 81 classes into 82 classes?

**Comment by tamtamz** [comment]
I fixed the parameter converter for the 82-way object classifier. See the section of the parameter conversion in the README.

**Comment by weiyunfei** [comment]
Cool! Thanks a lot.
